### ISSUE TITLE
Missing Front-End Codegen

### ISSUE THREAD

**Issue by Stevenje** [chagadev/fullstack-boilerplate#17]
During the transition to Fastify - I think we lost the front end codegen.

My current config:  

```yml
schema: ./packages/schema/generated/nexus-schema.graphql
require:
  - ts-node/register/transpile-only
generates:
  ./packages/frontend/src/generated/graphql-operations.ts:
    documents: "./packages/frontend/src/generated/**/*.gql"
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
```
